import { createContext, useContext, useEffect, useState } from "react";

const LANG_KEY = "nosee-accessibility-lang";

const SUPPORTED_LANGS = ["es-MX", "en-US"];

function readStoredLang() {
  try {
    const raw = window.localStorage.getItem(LANG_KEY);
    return raw && SUPPORTED_LANGS.includes(raw) ? raw : "es-MX";
  } catch {
    return "es-MX";
  }
}

// ── Traducciones completas ────────────────────────────────────────────────────
export const TRANSLATIONS = {
  "es-MX": {
    // ── Menú de accesibilidad ─────────────────────────────────────────────────
    a11y: {
      speechLang: "es-MX",
      triggerTitle: "Abrir menú de accesibilidad (Ctrl+U)",
      triggerLabel: "Abrir menú de accesibilidad",
      panelLabel: "Menú de accesibilidad",
      title: "Menú De Accesibilidad (CTRL+U)",
      closeLabel: "Cerrar menú",
      langButtonLabel: "🇨🇴 Español (Colombia) ▸",
      widgetLabel: "XL Widget de gran tamaño",
      fontSizeLabel: (pct) => `Tamaño actual de texto: ${pct}`,
      toolsLabel: "Herramientas de accesibilidad",
      prefsLabel: "Preferencias principales",
      decreaseText: "Reducir texto",
      stopReadingLabel: "Detener lectura",
      resetLabel: "Restablecer ajustes",
      features: {
        readPage: "Leer página",
        highContrast: "Contraste +",
        smartContrast: "Contraste inteligente",
        highlightLinks: "Resaltar enlaces",
        biggerText: "Agrandar texto",
        textSpacing: "Espaciado de texto",
        pauseAnimations: "Detener animaciones",
        hideImages: "Ocultar imágenes",
        readableFont: "Apto para dislexia",
        cursor: "Cursor",
        info: "Información",
        pageStructure: "Estructura de la página",
        lineHeight: "Altura de la línea",
        textAlignLeft: "Texto alineado",
        lightMode: "Modo día",
        nightMode: "Modo noche",
      },
      announces: {
        notAvailable: "La lectura en voz no está disponible en este navegador.",
        noContent: "No hay contenido disponible para leer.",
        reading: "Leyendo contenido de la página.",
        stopped: "Lectura detenida.",
        reset: "Ajustes de accesibilidad restablecidos.",
      },
      infoPanel: {
        title: "Acerca de este menú",
        description:
          "Este menú cumple con las pautas WCAG 2.1 nivel AA. Permite ajustar la apariencia y comportamiento de la página para mejorar tu experiencia de navegación.",
        shortcutsTitle: "Atajos de teclado",
        shortcuts: [
          { keys: "Ctrl + U", action: "Abrir / cerrar este menú" },
          { keys: "Escape", action: "Cerrar el menú" },
        ],
        featuresTitle: "Funciones disponibles",
        features: [
          "Contraste alto e inteligente",
          "Escalado de texto (90 % – 160 %)",
          "Espaciado y altura de línea",
          "Fuente apta para dislexia",
          "Resaltar enlaces",
          "Ocultar imágenes",
          "Detener animaciones",
          "Cursor ampliado",
          "Estructura de la página",
          "Lectura en voz alta",
          "Modo día / noche",
        ],
        closeInfo: "Cerrar información",
      },
    },

    // ── Navegación ────────────────────────────────────────────────────────────
    nav: {
      label: "Navegación principal",
      home: "Inicio",
      products: "Productos",
      stores: "Tiendas",
      panelAdmin: "Panel Admin",
      moderation: "Moderación",
      myOrders: "Mis Pedidos",
      login: "Iniciar sesión",
      register: "Registrarse",
      myProfile: "Mi perfil",
      logout: "Cerrar sesión",
      ranking: "Ranking",
    },

    // ── Ranking ───────────────────────────────────────────────────────────────
    ranking: {
      title: "Ranking de reputación",
      subtitle: "Los usuarios más activos y confiables de la comunidad",
      position: "Posición",
      user: "Usuario",
      points: "Puntos",
      noUsers: "No hay usuarios aún",
      loading: "Cargando ranking...",
      error: "Error al cargar el ranking",
      role: "Rol",
    },

    // ── Celebración ───────────────────────────────────────────────────────────
    celebration: {
      publication: "¡Publicación creada! +5 puntos de reputación",
      store: "¡Tienda registrada! +3 puntos de reputación",
      product: "¡Producto registrado! +2 puntos de reputación",
      brand: "¡Marca registrada! +1 punto de reputación",
      comment: "¡Comentario agregado! +1 punto de reputación",
      close: "Cerrar",
      congrats: "¡Felicitaciones!",
    },

    // ── Página principal ──────────────────────────────────────────────────────
    home: {
      title: "Bienvenidos a NØSEE, plataforma colaborativa.",
      subtitle: "No sabes donde es más barato, te mostramos donde no ves.",
      loginCta: "Inicia sesión para crear y votar publicaciones.",
      loading: "Cargando publicaciones...",
      noPublications:
        "Aún no hay publicaciones. Cuando un usuario cree una, aparecerá aquí.",
      validate: "✓ Validar",
      validated: "✓ Validado",
      report: "🚩 Reportar",
      viewMore: "Ver más",
      deleteBtn: "🗑 Eliminar",
      loginToVote: "Inicia sesión para votar",
      loginToReport: "Inicia sesión para reportar",
      removeValidation: "Quitar validación",
      validatePrice: "Validar precio",
      validateLabel: (name) => `Validar precio de ${name}`,
      removeValidationLabel: (name) => `Quitar validación de ${name}`,
      reportLabel: (name) => `Reportar ${name}`,
      deleteLabel: (name) => `Eliminar publicación ${name}`,
      detailLabel: (name) => `Ver detalle de ${name}`,
      noDescription: "Sin descripción",
      product: "Producto",
      store: "Tienda",
      sending: "Enviando...",
      close: "Cerrar",
      price: "Precio:",
      storeLabel: "Tienda:",
      description: "Descripción:",
      reportPublication: "Reportar publicación",
      reportDescription: "Selecciona un motivo para reportar la publicación.",
      reportReason: "Motivo del reporte",
      selectReason: "Seleccionar motivo...",
      fakePrice: "Precio falso",
      wrongPhoto: "Foto incorrecta",
      spam: "Spam",
      offensive: "Contenido ofensivo",
      cancel: "Cancelar",
      confirmDelete: "¿Eliminar esta publicación?",
      closeDetail: "Cerrar detalle de publicación",
    },

    // ── Login ─────────────────────────────────────────────────────────────────
    loginPage: {
      title: "Bienvenido de nuevo",
      subtitle: "Compara precios con tu comunidad",
    },
    loginForm: {
      googleLogin: "Continuar con Google",
      orEmail: "o con email",
      resendConfirmation: "Reenviar email de confirmación",
      emailLabel: "Correo electrónico",
      emailPlaceholder: "tucorreo@ejemplo.com",
      passwordLabel: "Contraseña",
      forgotPassword: "¿Olvidaste tu contraseña?",
      loginButton: "Iniciar sesión",
      loggingIn: "Iniciando sesión...",
      noAccount: "¿No tienes cuenta?",
      registerFree: "Regístrate gratis",
      showPassword: "Mostrar contraseña",
      hidePassword: "Ocultar contraseña",
      emailRequired: "El email es requerido",
      emailInvalid: "Email inválido",
      passwordRequired: "La contraseña es requerida",
    },

    // ── Registro ──────────────────────────────────────────────────────────────
    registerPage: {
      title: "Crea tu cuenta",
      subtitle: "Únete y empieza a comparar precios",
      verifyTitle: "Verifica tu email",
      verifySent: "Enviamos un enlace de confirmación a:",
      verifyInstruction:
        "Revisa tu bandeja de entrada y haz clic en el enlace para activar tu cuenta.",
      emailResent: "✓ Email reenviado. Revisa tu bandeja.",
      resendEmail: "¿No llegó? Reenviar email",
      resending: "Reenviando...",
    },
    registerForm: {
      googleRegister: "Registrarme con Google",
      orForm: "o completa el formulario",
      fullNameLabel: "Nombre completo",
      fullNamePlaceholder: "Tu nombre y apellido",
      emailLabel: "Correo electrónico",
      emailPlaceholder: "tucorreo@ejemplo.com",
      passwordLabel: "Contraseña",
      passwordPlaceholder: "Mínimo 8 caracteres",
      confirmPasswordLabel: "Confirmar contraseña",
      confirmPasswordPlaceholder: "Repite tu contraseña",
      terms: "Al registrarte aceptas los",
      termsLink: "Términos de uso",
      and: "y la",
      privacyLink: "Política de privacidad",
      createAccount: "Crear cuenta",
      creatingAccount: "Creando cuenta...",
      hasAccount: "¿Ya tienes cuenta?",
      loginLink: "Inicia sesión",
      showPassword: "Mostrar contraseña",
      hidePassword: "Ocultar contraseña",
      fullNameRequired: "El nombre es requerido",
      emailRequired: "El email es requerido",
      emailInvalid: "Email inválido",
      passwordRequired: "La contraseña es requerida",
      passwordWeak: "La contraseña no cumple los requisitos",
      confirmRequired: "Confirma tu contraseña",
      passwordMismatch: "Las contraseñas no coinciden",
      passwordRules: ["Al menos 8 caracteres", "Una letra mayúscula", "Un número"],
      strongPassword: "Contraseña segura",
      mediumPassword: "Contraseña media",
      weakPassword: "Contraseña débil",
    },

    // ── Recuperar contraseña ──────────────────────────────────────────────────
    forgotPassword: {
      title: "Recuperar contraseña",
      subtitle: "Te enviaremos un enlace para restablecerla",
      emailLabel: "Correo electrónico",
      emailPlaceholder: "tucorreo@ejemplo.com",
      sendButton: "Enviar enlace de recuperación",
      sending: "Enviando enlace...",
      rememberPassword: "¿Recordaste tu contraseña?",
      backToLogin: "Inicia sesión",
      successTitle: "Revisa tu correo",
      successSent: "Enviamos un enlace de recuperación a:",
      successInstruction:
        "Haz clic en el enlace del correo para crear tu nueva contraseña. Si no lo ves, revisa la carpeta de spam.",
      backToLoginLink: "← Volver al inicio de sesión",
      emailRequired: "El email es requerido",
      emailInvalid: "Email inválido",
      serverError: "No se pudo enviar el correo. Intenta más tarde.",
    },

    // ── Perfil ────────────────────────────────────────────────────────────────
    profile: {
      title: "Mi perfil",
      subtitle: "Gestiona tu información personal",
      securityTitle: "Seguridad y sesión",
      changePassword: "Cambiar contraseña",
      logout: "Cerrar sesión",
      dangerZoneTitle: "Zona peligrosa",
      dangerZoneDesc:
        "Puedes desactivar tu cuenta o eliminarla permanentemente. Si tienes publicaciones, te explicaremos qué pasa con ellas antes de confirmar.",
      deleteAccount: "Eliminar cuenta",
      deleteModalTitle: "¿Qué quieres hacer con tu cuenta?",
      deleteModalSubtitle:
        "Tus publicaciones ayudan a la comunidad a encontrar mejores precios.",
      deactivateTitle: "🔒 Desactivar mi cuenta",
      deactivateDesc:
        "Tu cuenta se desactiva y no podrás iniciar sesión. Tus publicaciones permanecerán visibles para seguir ayudando a la comunidad con precios reales.",
      permanentTitle: "🗑 Eliminar cuenta permanentemente",
      permanentDesc:
        "Se eliminan tu cuenta y todos tus datos: publicaciones, votos, tiendas, historial. Esta acción es irreversible.",
      cancel: "Cancelar",
      confirmDeactivateTitle: "Confirmar desactivación",
      confirmDeactivateInfo:
        "ℹ️ Tu cuenta quedará desactivada y no podrás iniciar sesión.",
      confirmDeactivateDetail:
        "Tus publicaciones seguirán visibles para ayudar a la comunidad a comparar precios reales. Nadie sabrá que tu cuenta está desactivada.",
      back: "Atrás",
      confirmDeactivate: "Sí, desactivar mi cuenta",
      processing: "Procesando...",
      permanentModalTitle: "⚠️ Eliminación permanente",
      permanentWarning: "Esta acción no se puede deshacer. Se eliminarán permanentemente:",
      permanentItems: [
        "Tu cuenta y acceso",
        "Todas tus publicaciones de precios",
        "Tus votos y reportes",
        "Tus tiendas creadas y sus evidencias",
        "Tu historial completo",
      ],
      confirmPermanent: "Sí, eliminar todo permanentemente",
      deleting: "Eliminando...",
      priceAlerts: {
        title: "Alertas de precios",
        description: "Te notificaremos cuando un producto baje del precio que indiques.",
        productIdLabel: "ID del producto",
        productIdPlaceholder: "Ej: 42",
        targetPriceLabel: "Precio objetivo",
        targetPricePlaceholder: "Ej: 5000",
        required: "(obligatorio)",
        saving: "Guardando...",
        addAlert: "+ Agregar alerta",
        loading: "Cargando alertas...",
        empty: "No tienes alertas activas.",
        listLabel: "Tus alertas de precio activas",
        delete: "Eliminar",
        deleteAriaLabel: (name, price) => `Eliminar alerta de ${name} a $${price}`,
        unknownProduct: (id) => `Producto #${id}`,
      },
    },

    // ── App / General ─────────────────────────────────────────────────────────
    app: {
      skipToContent: "Saltar al contenido principal",
      loading: "Iniciando aplicación...",
      loadingPage: "Cargando...",
      notFound: "Página no encontrada",
      backHome: "Volver al inicio",
      roleChangePrefix: "Tu rol ha sido actualizado a:",
      closeNotification: "Cerrar notificación",
      connectionErrorTitle: "Sin conexión a internet",
      connectionErrorMessage: "No pudimos conectarnos al servidor.",
      connectionErrorHint: "Verifica tu conexión e intenta nuevamente.",
    },

    // ── Subida de fotos ───────────────────────────────────────────────────────
    photoUploader: {
      groupLabel: "Opciones para agregar foto",
      galleryLabel: "Subir imagen desde la galería del dispositivo",
      galleryButton: "Subir desde galería",
      cameraLabel: "Abrir cámara para tomar una foto",
      cameraButton: "Tomar foto",
      uploading: "Subiendo foto...",
      success: "Foto subida correctamente",
      changePhoto: "Cambiar foto",
      errorTitle: "Error al subir foto",
      dismissError: "Descartar error",
      retry: "Intentar de nuevo",
    },

    // ── Publicaciones ─────────────────────────────────────────────────────────
    publications: {
      title: "Productos",
      subtitle: "Busca y compara los mejores precios de productos en la región. Ayuda a la comunidad compartiendo publicaciones útiles.",
      createBtn: "Crear publicación",
      verifyEmailError: "Debes verificar tu email antes de publicar",
      verifyEmailWarning: "⚠️ Verifica tu email para publicar precios. Revisa tu bandeja de entrada.",
      verifyEmailTitle: "Verifica tu email primero",
      searchPlaceholder: "Buscar producto, tienda o precio...",
      loading: "Cargando publicaciones...",
      loadingDetail: "Cargando detalle...",
      noPublicationsTitle: "No hay publicaciones",
      noPublicationsDesc: "No encontramos publicaciones que coincidan con tus filtros. Intenta con otros términos o",
      beFirst: "sé el primero en publicar",
      loadMore: "Ver más publicaciones",
      errorValidate: "No se pudo validar la publicación",
      errorReport: "No se pudo reportar la publicación",
      errorDelete: "No se pudo eliminar la publicación",
      errorDetail: "No se pudo cargar el detalle de la publicación",
    },

    // ── Tarjeta de publicación ────────────────────────────────────────────────
    publicationCard: {
      unknownProduct: "Producto desconocido",
      noStore: "Sin tienda",
      user: "Usuario",
      validations: "validaciones",
      reports: "reportes",
      validating: "Validando...",
      validate: "✓ Validar",
      validated: "✓ Validado",
      report: "⚠ Reportar",
      delete: "🗑 Eliminar",
      deleting: "...",
      viewMore: "Ver más",
      photoExpand: "🔍 Expandir",
      notAvailable: "Publicación no disponible",
      confirmDelete: "¿Eliminar publicación?",
      reportTitle: "Reportar publicación",
      reportTypeLabel: "Tipo de reporte:",
      reportSelect: "Seleccionar...",
      fakePrice: "Precio falso",
      wrongPhoto: "Foto incorrecta",
      spam: "Spam",
      offensive: "Contenido ofensivo",
      cancel: "Cancelar",
      sending: "Enviando...",
      expand: "Expandir",
      collapse: "Contraer",
      closePhotoLabel: "Cerrar foto ampliada",
      validateLabel: (name) => `Validar publicación de ${name}`,
      reportLabel: (name) => `Reportar publicación de ${name}`,
      deleteLabel: (name) => `Eliminar publicación de ${name}`,
      viewMoreLabel: (name) => `Ver más detalles de ${name}`,
      photoExpandLabel: (expanded, name) => `${expanded ? "Contraer" : "Expandir"} foto de ${name}`,
    },

    // ── Filtro de precios ─────────────────────────────────────────────────────
    priceFilter: {
      title: "Filtros",
      product: "🛒 Producto",
      store: "🏪 Tienda",
      productPlaceholder: "Buscar producto...",
      storePlaceholder: "Buscar tienda...",
      minPrice: "💰 Precio mínimo",
      maxPrice: "💰 Precio máximo",
      distance: "📍 Distancia máxima (km)",
      distancePlaceholder: "Sin límite",
      sortBy: "📊 Ordenar por",
      recent: "Más reciente",
      validated: "Más validadas",
      cheapest: "Más barato",
      clearFilters: "🗑 Limpiar filtros",
      activeFilter: "1 filtro activo",
      activeFilters: (n) => `${n} filtros activos`,
      maxLabel: (val) => `Máx $${val}`,
    },

    // ── Tiendas ───────────────────────────────────────────────────────────────
    storesPage: {
      title: "Tiendas",
      subtitle: "Explora las tiendas registradas por la comunidad.",
      createBtn: "Crear tienda",
      createBtnLabel: "Crear nueva tienda",
      empty: "Aún no hay tiendas registradas.",
      comingSoon: "El listado de tiendas estará disponible próximamente.",
      searchPlaceholder: "Buscar tienda por nombre...",
      loading: "Cargando tiendas...",
      errorLoading: "Error al cargar tiendas",
      physical: "Física",
      virtual: "Virtual",
      viewDetail: "Ver detalle",
      storeDetail: {
        title: "Detalle de tienda",
        close: "Cerrar",
        address: "Dirección",
        website: "Sitio web",
        noAddress: "Sin dirección registrada",
        type: "Tipo",
        featuredProducts: "Publicaciones recientes",
        noProducts: "Sin publicaciones aún",
        mapLoadError: "No se pudo cargar el mapa",
        noLocation: "Tienda virtual – sin ubicación física",
        loadingProducts: "Cargando publicaciones...",
        visitWebsite: "Visitar sitio web",
        evidences: "Fotos de la tienda",
        noEvidences: "Sin fotos de evidencia registradas.",
      },
    },

    // ── Crear tienda ──────────────────────────────────────────────────────────
    createStore: {
      title: "🏪 Crear tienda",
      subtitle: "Registra una tienda física o virtual. Para tiendas físicas puedes adjuntar hasta 3 evidencias.",
    },

    // ── Formulario de tienda ──────────────────────────────────────────────────
    storeForm: {
      nameLabel: "Nombre de la tienda",
      namePlaceholder: "Ej: Supermercado Central",
      typeLabel: "Tipo de tienda",
      urlLabel: "URL de la tienda virtual",
      urlPlaceholder: "https://mitienda.com",
      submit: "Crear tienda",
      submitting: "Creando tienda...",
    },

    // ── Tipo de tienda ────────────────────────────────────────────────────────
    storeType: {
      physical: "🏬 Tienda física",
      virtual: "🌐 Tienda virtual",
      ariaLabel: "Tipo de tienda",
    },

    // ── Mapa de tienda ────────────────────────────────────────────────────────
    storeMap: {
      title: "📍 Ubicación del local",
      addressPlaceholder: "Ej: Calle 10 #25-30, Bogotá",
      searchBtn: "Buscar dirección",
      latPlaceholder: "Latitud",
      lonPlaceholder: "Longitud",
      applyBtn: "Aplicar",
      useLocationBtn: "Usar mi ubicación actual",
      gettingLocation: "Obteniendo ubicación…",
      centerMap: "Centrar mapa",
      viewOSM: "Ver punto en OpenStreetMap",
      footer: "Visualizador: Leaflet + OpenStreetMap. Geocodificación: Nominatim (gratis con límites de uso).",
      statusResolving: "Resolviendo dirección...",
      statusAddressUpdated: "Dirección actualizada desde la ubicación seleccionada.",
      statusInvalidCoords: "Ingresa latitud y longitud válidas.",
      statusSearching: "Buscando dirección...",
      statusFound: "Dirección encontrada y ubicación actualizada.",
      statusNoAddress: "Escribe una dirección para buscarla.",
      statusGetting: "Obteniendo ubicación...",
      statusCenterSelect: "Selecciona una ubicación válida para centrar el mapa.",
      statusCentered: "Mapa centrado en la ubicación seleccionada.",
      geoPrefix: "Geo:",
    },

    // ── Evidencias de tienda ──────────────────────────────────────────────────
    storeEvidence: {
      title: "🖼 Evidencias del local",
      addEvidence: "Agregar evidencia",
      limitReached: "Límite alcanzado (máximo 3 imágenes)",
      remove: "Quitar",
      altText: "Evidencia",
    },

    // ── Detalle de publicación ────────────────────────────────────────────────
    publicationDetail: {
      closeModal: "Cerrar detalle de publicación",
      noName: "Producto sin nombre",
      unit: "Unidad:",
      noDescription: "No hay descripción",
      publishedBy: "Publicado por:",
      unknownUser: "Usuario desconocido",
      score: "Puntaje:",
      votes: "Votos:",
      comments: "Comentarios",
      noComments: "Sin comentarios por ahora.",
      commentPlaceholder: "Escribe un comentario...",
      replyPlaceholder: "Escribe tu respuesta...",
      addCommentBtn: "Comentar",
      replyBtn: "Responder",
      cancelReply: "Cancelar",
      deleteComment: "Eliminar",
      replyingTo: "Respondiendo a",
      loginToComment: "Inicia sesión para comentar.",
      storeLocation: "Ubicación de la tienda",
      noCoordinates: "No hay coordenadas disponibles para esta tienda.",
      virtualStoreLink: "Ir al enlace de la tienda virtual",
      mapAria: "Mapa de ubicación de tienda",
      mapError: "Error en el mapa:",
      mapErrorDetails: "Revisa la consola (F12) para más detalles",
    },

    // ── Tiempo relativo ───────────────────────────────────────────────────────
    timeAgo: {
      justNow: "hace unos segundos",
      minutes: (n) => `hace ${n} minuto${n !== 1 ? "s" : ""}`,
      hours: (n) => `hace ${n} hora${n !== 1 ? "s" : ""}`,
      days: (n) => `hace ${n} día${n !== 1 ? "s" : ""}`,
      weeks: (n) => `hace ${n} semana${n !== 1 ? "s" : ""}`,
      months: (n) => `hace ${n} mes${n !== 1 ? "es" : ""}`,
      years: (n) => `hace ${n} año${n !== 1 ? "s" : ""}`,
    },

    // ── Formulario de publicación ─────────────────────────────────────────────
    publicationForm: {
      title: "Publicar Precio",
      success: "✓ Publicación creada exitosamente",
      errorFallback: "Error al crear publicación",
      unknownError: "Error desconocido",
      productLabel: "Producto",
      productPlaceholder: "Escribe el nombre del producto...",
      storeLabel: "Tienda",
      storePlaceholder: "Escribe el nombre de la tienda...",
      searching: "Buscando...",
      noResults: "Sin resultados",
      createProduct: (name) => `+ Crear "${name}"`,
      createStore: (name) => `+ Crear tienda "${name}"`,
      productSelected: "✓ Producto seleccionado",
      storeSelected: "✓ Tienda seleccionada",
      productRequired: "Selecciona o crea un producto",
      storeRequired: "Selecciona o crea una tienda",
      priceLabel: "Precio",
      currencyLabel: "Moneda",
      descriptionLabel: "Descripción (opcional)",
      descriptionPlaceholder: "Ej: Buen estado, precio justo",
      photoLabel: "Foto del producto",
      geoDetected: "Ubicación detectada:",
      submitting: "Publicando...",
      submitBtn: "Confirmar publicación",
      priceRequired: "El precio debe ser mayor a 0",
      photoRequired: "La foto es obligatoria",
      descriptionMax: "Máximo 500 caracteres",
    },

    // ── Dashboard Admin ───────────────────────────────────────────────────────
    adminDashboard: {
      navOverview: "Resumen",
      navUsers: "Usuarios",
      navContent: "Contenido",
      navReports: "Reportes",
      navConfig: "Config",
      overviewTitle: "Panel de control",
      overviewSub: "Vista general de la plataforma NØSEE",
      statUsers: "Usuarios totales",
      statPubs: "Publicaciones hoy",
      statValidations: "Validaciones hoy",
      statReports: "Reportes pendientes",
      recentUsers: (n) => `Usuarios recientes (${n})`,
      viewAll: "Ver todos →",
      noUsers: "No hay usuarios registrados aún",
      usersTitle: "Gestión de usuarios",
      usersCount: (n) => `${n} usuarios registrados`,
      loadingDots: "Cargando...",
      loadingUsers: "Cargando usuarios...",
      contentTitle: "Gestión de contenido",
      contentSub: "Publicaciones de precios en la plataforma — el admin puede eliminar cualquiera",
      filterAll: "Todas",
      filterActive: "Activas",
      filterPending: "Pendientes",
      filterExpired: "Expiradas",
      loadingPubs: "Cargando publicaciones...",
      noPubsView: "No hay publicaciones en esta vista",
      reportsTitle: "Reportes de la comunidad",
      reportsSub: (n, r) => `${n} reportes • ${r} resueltos en esta sesión`,
      reportsAllDone: (r) => `Todo revisado — ${r} resueltos en esta sesión`,
      reportsNone: "Sin reportes en esta vista",
      filterPendingReports: "Pendientes",
      filterResolved: "Resueltos",
      filterAllReports: "Todos",
      filterStatusLabel: "Estado",
      filterTypeLabel: "Tipo de reporte",
      filterSortLabel: "Orden",
      sortRecent: "Más recientes",
      sortOldest: "Más antiguos",
      summaryByStatus: "Cantidad por estado",
      summaryByType: "Cantidad por tipo",
      statusLabels: {
        PENDING: "Pendiente",
        IN_REVIEW: "En revisión",
        RESOLVED: "Resuelto",
        REJECTED: "Rechazado",
      },
      noReportsPending: "Sin reportes pendientes ✓",
      loadingReports: "Cargando reportes...",
      configTitle: "Configuración del sistema",
      configSub: "Parámetros globales de la plataforma NØSEE",
      repTitle: "Sistema de reputación",
      cancel: "Cancelar",
      save: "Guardar",
      editBtn: "✎ Editar",
      catsTitle: "Categorías de productos",
      catsCount: (n) => `${n} categorías`,
      newCatPlaceholder: "Nombre de nueva categoría...",
      createBtn: "+ Crear",
      loadingCats: "Cargando categorías...",
      noCats: "No hay categorías registradas",
      productsCount: (n) => `${n} productos`,
      banTitle: "⊗ Banear usuario",
      unbanTitle: "✓ Desbanear usuario",
      banDesc1: "Vas a banear a",
      banDesc2: ". Su cuenta quedará bloqueada y",
      banDescStrong: "todas sus publicaciones activas serán ocultadas",
      banDesc3: ".",
      unbanDesc1: "Vas a restaurar el acceso de",
      unbanDesc2: ". Podrá volver a iniciar sesión normalmente.",
      cancelBtn: "Cancelar",
      confirmBanBtn: "Sí, banear",
      confirmUnbanBtn: "Sí, desbanear",
      reportTypes: {
        fake_price: "Precio falso",
        wrong_photo: "Foto incorrecta",
        spam: "Spam",
        offensive: "Contenido ofensivo",
      },
      severityLabels: { alta: "ALTA", media: "MEDIA", baja: "BAJA" },
      colUser: "Usuario",
      colRole: "Rol",
      colRep: "Rep.",
      colStatus: "Estado",
      colActions: "Acciones",
      colProduct: "Producto",
      colStore: "Tienda",
      colPrice: "Precio",
      colAuthor: "Autor",
      colDate: "Fecha",
      colAction: "Acción",
      savingRole: "Guardando...",
      banBtn: "Banear",
      unbanBtn: "Desbanear",
      statusActive: "activo",
      statusBanned: "baneado",
      resolvedBadge: "RESUELTO",
      labelPublication: "Publicación",
      labelReportedBy: "Reportado por",
      labelReportedUser: "Usuario denunciado",
      deletePublicationBtn: "🗑 Eliminar publicación",
      banUserBtn: "⊗ Banear usuario",
      dismissBtn: "↩ Descartar",
      viewReportDetailBtn: "Ver detalle",
      reportDetailTitle: "Detalle de reporte",
      reportDetailSubtitle: (id) => `ID: ${id}`,
      labelDescription: "Descripción",
      labelEvidence: "Evidencia",
      labelActionTaken: "Acción tomada",
      labelModNotes: "Notas del moderador",
      saveReportBtn: "Guardar revisión",
      reportSavedOk: "Revisión guardada correctamente",
      pubStatusActive: "activa",
      pubStatusPending: "pendiente",
      pubStatusRejected: "rechazada",
      pubStatusExpired: "expirada",
      pubVisible: "Visible",
      pubHiddenStatus: "Oculta",
      filterVisible: "Visibles",
      filterHidden: "Ocultas",
      pubTotalLabel: (n) => `${n} publicaciones en total`,
      pubHiddenLabel: (n) => `${n} no visibles`,
      viewPubBtn: "Ver detalle",
      editPubTitle: "Editar publicación",
      pubDetailTitle: "Detalle de publicación",
      pubVisibilityLabel: "Visibilidad",
      pubPriceLabel: "Precio",
      pubProductLabel: "Producto",
      pubStoreLabel: "Tienda",
      pubAuthorLabel: "Autor",
      pubRepLabel: "Reputación",
      pubDateLabel: "Publicado",
      pubDescriptionLabel: "Descripción",
      pubConfidenceLabel: "Confiabilidad",
      pubIsActiveLabel: "Visible en la plataforma",
      pubIsHiddenLabel: "Oculta (no visible)",
      toggleVisibleBtn: "Mostrar publicación",
      toggleHideBtn: "Ocultar publicación",
      savePubBtn: "Guardar cambios",
      pubSavedOk: "Publicación actualizada correctamente",
      errorEditPub: (e) => `Error al editar: ${e}`,
      errorEditPubGeneric: "Error al editar la publicación.",
      noName: "Sin nombre",
      confirmDeletePub: "¿Eliminar esta publicación permanentemente?",
      errorChangeRole: (e) => `Error al cambiar rol: ${e}`,
      errorChangeRoleGeneric: "Error al cambiar rol. Intenta de nuevo.",
      errorLoadUsers: "No se pudieron cargar los usuarios",
      errorConnect: "Error al conectar con el servidor",
      retry: "Reintentar",
      errorStatus: "Error al cambiar estado.",
      errorDeletePub: (e) => `Error al eliminar: ${e}`,
      errorDeletePubGeneric: "Error al eliminar la publicación.",
      errorUpdateReport: "No se pudo actualizar el reporte",
      errorCreateCat: (e) => e || "Error al crear categoría",
      deletedPub: "Publicación eliminada",
      anonymous: "Anónimo",
      unknown: "Desconocido",
    },

    // ── Dashboard Moderador ───────────────────────────────────────────────────
    moderatorDashboard: {
      navReports: "Reportes",
      navFeed: "Feed",
      navHistory: "Historial",
      reportsTitle: "Reportes pendientes",
      reportsSub: (n) => `${n} reportes esperan revisión`,
      reportsAllDone: "Todo al día ✓",
      resolvedToday: (n) => `${n} resueltos hoy`,
      loadingReports: "Cargando reportes...",
      noReportsTitle: "Sin reportes pendientes",
      noReportsSub: "La plataforma está limpia. Buen trabajo.",
      feedTitle: "Feed con controles de moderación",
      feedSub: "Ver todas las publicaciones con opciones para eliminar o banear contenido",
      historyTitle: "Historial de acciones",
      historySub: "Registro de todas las moderaciones realizadas por este moderador",
      comingSoon: "Próximamente",
      labelPublication: "Publicación",
      labelReportedBy: "Reportado por",
      labelReportedUser: "Usuario denunciado",
      deletePublicationBtn: "🗑 Eliminar publicación",
      banUserBtn: "⊗ Banear usuario",
      dismissBtn: "↩ Descartar",
      reportTypes: {
        fake_price: "Precio falso",
        wrong_photo: "Foto incorrecta",
        spam: "Spam",
        offensive: "Contenido ofensivo",
      },
      severityLabels: { alta: "ALTA", media: "MEDIA", baja: "BAJA" },
      statusLabels: {
        PENDING: "Pendiente",
        IN_REVIEW: "En revisión",
        RESOLVED: "Resuelto",
        REJECTED: "Rechazado",
      },
      viewReportDetailBtn: "Ver detalle",
      reportDetailTitle: "Detalle de reporte",
      reportDetailSubtitle: (id) => `ID: ${id}`,
      filterStatusLabel: "Estado",
      labelDescription: "Descripción",
      labelEvidence: "Evidencia",
      labelActionTaken: "Acción tomada",
      labelModNotes: "Notas del moderador",
      saveReportBtn: "Guardar revisión",
      reportSavedOk: "Revisión guardada correctamente",
      cancel: "Cancelar",
      errorUpdateReport: "No se pudo actualizar el reporte",
      actionConfirmBan: (user) => `Vas a banear a ${user}. Su cuenta quedará bloqueada.`,
      actionConfirmDismiss: "Vas a descartar este reporte.",
      actionConfirmTitle: "Confirmar acción",
      actionNotesLabel: "Notas internas (opcional)",
      actionConfirmBtn: "Confirmar",
      deletedPub: "Publicación eliminada",
      anonymous: "Anónimo",
      unknown: "Desconocido",
    },

    // ── Dashboard Repartidor ──────────────────────────────────────────────────
    dealerDashboard: {
      onlineLabel: "En línea",
      navActive: "Pedidos activos",
      navRoute: "Mi ruta",
      navHistory: "Historial",
      navEarnings: "Ganancias",
      statActive: "Activos",
      statToday: "Hoy",
      statEarned: "Ganado",
      activeTitle: "Pedidos activos",
      activeSub: (n) => `${n} en curso`,
      noOrders: "Sin pedidos activos. Espera nuevas asignaciones.",
      historyTitle: "Historial de pedidos",
      historySub: "Tus últimas entregas",
      routeTitle: "Mapa de ruta",
      routeSub: "Visualización de ruta óptima entre tiendas y destinos",
      earningsTitle: "Panel de ganancias",
      earningsSub: "Resumen de ganancias diarias, semanales y comisiones",
      comingSoon: "Próximamente",
      statusPendiente: "Pendiente",
      statusComprando: "Comprando",
      statusEnCamino: "En camino",
      statusLlegando: "Llegando",
      statusEntregado: "Entregado",
      statusCancelado: "Cancelado",
      nextPendiente: "Iniciar compra →",
      nextComprando: "Salir a entregar →",
      nextEnCamino: "Llegué →",
      nextLlegando: "Marcar entregado ✓",
      advance: "Avanzar →",
    },
  },

  // ── INGLÉS ────────────────────────────────────────────────────────────────
  "en-US": {
    // ── Menú de accesibilidad ─────────────────────────────────────────────────
    a11y: {
      speechLang: "en-US",
      triggerTitle: "Open accessibility menu (Ctrl+U)",
      triggerLabel: "Open accessibility menu",
      panelLabel: "Accessibility menu",
      title: "Accessibility Menu (CTRL+U)",
      closeLabel: "Close menu",
      langButtonLabel: "🇺🇸 English (USA) ▸",
      widgetLabel: "XL Large widget",
      fontSizeLabel: (pct) => `Current text size: ${pct}`,
      toolsLabel: "Accessibility tools",
      prefsLabel: "Main preferences",
      decreaseText: "Decrease text",
      stopReadingLabel: "Stop reading",
      resetLabel: "Reset settings",
      features: {
        readPage: "Read page",
        highContrast: "High contrast",
        smartContrast: "Smart contrast",
        highlightLinks: "Highlight links",
        biggerText: "Bigger text",
        textSpacing: "Text spacing",
        pauseAnimations: "Pause animations",
        hideImages: "Hide images",
        readableFont: "Dyslexia friendly",
        cursor: "Cursor",
        info: "Information",
        pageStructure: "Page structure",
        lineHeight: "Line height",
        textAlignLeft: "Align text left",
        lightMode: "Day mode",
        nightMode: "Night mode",
      },
      announces: {
        notAvailable: "Text-to-speech is not available in this browser.",
        noContent: "No content available to read.",
        reading: "Reading page content.",
        stopped: "Reading stopped.",
        reset: "Accessibility settings reset.",
      },
      infoPanel: {
        title: "About this menu",
        description:
          "This menu complies with WCAG 2.1 Level AA guidelines. It lets you adjust the page's appearance and behavior to improve your browsing experience.",
        shortcutsTitle: "Keyboard shortcuts",
        shortcuts: [
          { keys: "Ctrl + U", action: "Open / close this menu" },
          { keys: "Escape", action: "Close the menu" },
        ],
        featuresTitle: "Available features",
        features: [
          "High and smart contrast",
          "Text scaling (90 % – 160 %)",
          "Text spacing and line height",
          "Dyslexia-friendly font",
          "Highlight links",
          "Hide images",
          "Pause animations",
          "Bigger cursor",
          "Page structure outline",
          "Text-to-speech",
          "Day / night mode",
        ],
        closeInfo: "Close information",
      },
    },

    // ── Navegación ────────────────────────────────────────────────────────────
    nav: {
      label: "Main navigation",
      home: "Home",
      products: "Products",
      stores: "Stores",
      panelAdmin: "Admin Panel",
      moderation: "Moderation",
      myOrders: "My Orders",
      login: "Sign in",
      register: "Sign up",
      myProfile: "My profile",
      logout: "Sign out",
      ranking: "Ranking",
    },

    // ── Ranking ───────────────────────────────────────────────────────────────
    ranking: {
      title: "Reputation Ranking",
      subtitle: "The most active and trustworthy users in the community",
      position: "Position",
      user: "User",
      points: "Points",
      noUsers: "No users yet",
      loading: "Loading ranking...",
      error: "Error loading ranking",
      role: "Role",
    },

    // ── Celebration ───────────────────────────────────────────────────────────
    celebration: {
      publication: "Publication created! +5 reputation points",
      store: "Store registered! +3 reputation points",
      product: "Product registered! +2 reputation points",
      brand: "Brand registered! +1 reputation point",
      comment: "Comment added! +1 reputation point",
      close: "Close",
      congrats: "Congratulations!",
    },

    // ── Página principal ──────────────────────────────────────────────────────
    home: {
      title: "Welcome to NØSEE, collaborative platform.",
      subtitle: "You don't know where it's cheaper, we show you where you can't see.",
      loginCta: "Sign in to create and vote on publications.",
      loading: "Loading publications...",
      noPublications:
        "No publications yet. When a user creates one, it will appear here.",
      validate: "✓ Validate",
      validated: "✓ Validated",
      report: "🚩 Report",
      viewMore: "View more",
      deleteBtn: "🗑 Delete",
      loginToVote: "Sign in to vote",
      loginToReport: "Sign in to report",
      removeValidation: "Remove validation",
      validatePrice: "Validate price",
      validateLabel: (name) => `Validate price of ${name}`,
      removeValidationLabel: (name) => `Remove validation of ${name}`,
      reportLabel: (name) => `Report ${name}`,
      deleteLabel: (name) => `Delete publication ${name}`,
      detailLabel: (name) => `View detail of ${name}`,
      noDescription: "No description",
      product: "Product",
      store: "Store",
      sending: "Sending...",
      close: "Close",
      price: "Price:",
      storeLabel: "Store:",
      description: "Description:",
      reportPublication: "Report publication",
      reportDescription: "Select a reason to report the publication.",
      reportReason: "Report reason",
      selectReason: "Select reason...",
      fakePrice: "False price",
      wrongPhoto: "Wrong photo",
      spam: "Spam",
      offensive: "Offensive content",
      cancel: "Cancel",
      confirmDelete: "Delete this publication?",
      closeDetail: "Close publication detail",
    },

    // ── Login ─────────────────────────────────────────────────────────────────
    loginPage: {
      title: "Welcome back",
      subtitle: "Compare prices with your community",
    },
    loginForm: {
      googleLogin: "Continue with Google",
      orEmail: "or with email",
      resendConfirmation: "Resend confirmation email",
      emailLabel: "Email address",
      emailPlaceholder: "youremail@example.com",
      passwordLabel: "Password",
      forgotPassword: "Forgot your password?",
      loginButton: "Sign in",
      loggingIn: "Signing in...",
      noAccount: "Don't have an account?",
      registerFree: "Sign up for free",
      showPassword: "Show password",
      hidePassword: "Hide password",
      emailRequired: "Email is required",
      emailInvalid: "Invalid email",
      passwordRequired: "Password is required",
    },

    // ── Registro ──────────────────────────────────────────────────────────────
    registerPage: {
      title: "Create your account",
      subtitle: "Join and start comparing prices",
      verifyTitle: "Verify your email",
      verifySent: "We sent a confirmation link to:",
      verifyInstruction:
        "Check your inbox and click the link to activate your account.",
      emailResent: "✓ Email resent. Check your inbox.",
      resendEmail: "Didn't receive it? Resend email",
      resending: "Resending...",
    },
    registerForm: {
      googleRegister: "Sign up with Google",
      orForm: "or complete the form",
      fullNameLabel: "Full name",
      fullNamePlaceholder: "Your first and last name",
      emailLabel: "Email address",
      emailPlaceholder: "youremail@example.com",
      passwordLabel: "Password",
      passwordPlaceholder: "Minimum 8 characters",
      confirmPasswordLabel: "Confirm password",
      confirmPasswordPlaceholder: "Repeat your password",
      terms: "By signing up you agree to the",
      termsLink: "Terms of use",
      and: "and the",
      privacyLink: "Privacy policy",
      createAccount: "Create account",
      creatingAccount: "Creating account...",
      hasAccount: "Already have an account?",
      loginLink: "Sign in",
      showPassword: "Show password",
      hidePassword: "Hide password",
      fullNameRequired: "Name is required",
      emailRequired: "Email is required",
      emailInvalid: "Invalid email",
      passwordRequired: "Password is required",
      passwordWeak: "Password does not meet requirements",
      confirmRequired: "Confirm your password",
      passwordMismatch: "Passwords do not match",
      passwordRules: ["At least 8 characters", "One uppercase letter", "One number"],
      strongPassword: "Strong password",
      mediumPassword: "Medium password",
      weakPassword: "Weak password",
    },

    // ── Recuperar contraseña ──────────────────────────────────────────────────
    forgotPassword: {
      title: "Recover password",
      subtitle: "We will send you a link to reset it",
      emailLabel: "Email address",
      emailPlaceholder: "youremail@example.com",
      sendButton: "Send recovery link",
      sending: "Sending link...",
      rememberPassword: "Remember your password?",
      backToLogin: "Sign in",
      successTitle: "Check your email",
      successSent: "We sent a recovery link to:",
      successInstruction:
        "Click the link in the email to create your new password. If you don't see it, check your spam folder.",
      backToLoginLink: "← Back to sign in",
      emailRequired: "Email is required",
      emailInvalid: "Invalid email",
      serverError: "Could not send the email. Please try again later.",
    },

    // ── Perfil ────────────────────────────────────────────────────────────────
    profile: {
      title: "My profile",
      subtitle: "Manage your personal information",
      securityTitle: "Security & session",
      changePassword: "Change password",
      logout: "Sign out",
      dangerZoneTitle: "Danger zone",
      dangerZoneDesc:
        "You can deactivate your account or delete it permanently. If you have publications, we will explain what happens to them before confirming.",
      deleteAccount: "Delete account",
      deleteModalTitle: "What do you want to do with your account?",
      deleteModalSubtitle:
        "Your publications help the community find better prices.",
      deactivateTitle: "🔒 Deactivate my account",
      deactivateDesc:
        "Your account is deactivated and you won't be able to sign in. Your publications will remain visible to continue helping the community with real prices.",
      permanentTitle: "🗑 Delete account permanently",
      permanentDesc:
        "Your account and all your data are deleted: publications, votes, stores, history. This action is irreversible.",
      cancel: "Cancel",
      confirmDeactivateTitle: "Confirm deactivation",
      confirmDeactivateInfo:
        "ℹ️ Your account will be deactivated and you won't be able to sign in.",
      confirmDeactivateDetail:
        "Your publications will remain visible to help the community compare real prices. No one will know your account is deactivated.",
      back: "Back",
      confirmDeactivate: "Yes, deactivate my account",
      processing: "Processing...",
      permanentModalTitle: "⚠️ Permanent deletion",
      permanentWarning: "This action cannot be undone. The following will be permanently deleted:",
      permanentItems: [
        "Your account and access",
        "All your price publications",
        "Your votes and reports",
        "Your created stores and their evidence",
        "Your complete history",
      ],
      confirmPermanent: "Yes, delete everything permanently",
      deleting: "Deleting...",
      priceAlerts: {
        title: "Price alerts",
        description: "We'll notify you when a product drops below the price you set.",
        productIdLabel: "Product ID",
        productIdPlaceholder: "E.g.: 42",
        targetPriceLabel: "Target price",
        targetPricePlaceholder: "E.g.: 5000",
        required: "(required)",
        saving: "Saving...",
        addAlert: "+ Add alert",
        loading: "Loading alerts...",
        empty: "You have no active alerts.",
        listLabel: "Your active price alerts",
        delete: "Delete",
        deleteAriaLabel: (name, price) => `Delete alert for ${name} at $${price}`,
        unknownProduct: (id) => `Product #${id}`,
      },
    },

    // ── App / General ─────────────────────────────────────────────────────────
    app: {
      skipToContent: "Skip to main content",
      loading: "Starting application...",
      loadingPage: "Loading...",
      notFound: "Page not found",
      backHome: "Back to home",
      roleChangePrefix: "Your role has been updated to:",
      closeNotification: "Close notification",
      connectionErrorTitle: "No internet connection",
      connectionErrorMessage: "We could not connect to the server.",
      connectionErrorHint: "Check your connection and try again.",
    },

    // ── Photo uploader ────────────────────────────────────────────────────────
    photoUploader: {
      groupLabel: "Options to add a photo",
      galleryLabel: "Upload image from device gallery",
      galleryButton: "Upload from gallery",
      cameraLabel: "Open camera to take a photo",
      cameraButton: "Take photo",
      uploading: "Uploading photo...",
      success: "Photo uploaded successfully",
      changePhoto: "Change photo",
      errorTitle: "Error uploading photo",
      dismissError: "Dismiss error",
      retry: "Try again",
    },

    // ── Publications ──────────────────────────────────────────────────────────
    publications: {
      title: "Products",
      subtitle: "Search and compare the best product prices in the region. Help the community by sharing useful publications.",
      createBtn: "Create publication",
      verifyEmailError: "You must verify your email before publishing",
      verifyEmailWarning: "⚠️ Verify your email to publish prices. Check your inbox.",
      verifyEmailTitle: "Verify your email first",
      searchPlaceholder: "Search product, store or price...",
      loading: "Loading publications...",
      loadingDetail: "Loading detail...",
      noPublicationsTitle: "No publications",
      noPublicationsDesc: "We found no publications matching your filters. Try other terms or",
      beFirst: "be the first to publish",
      loadMore: "Load more publications",
      errorValidate: "Could not validate the publication",
      errorReport: "Could not report the publication",
      errorDelete: "Could not delete the publication",
      errorDetail: "Could not load the publication detail",
    },

    // ── Publication card ──────────────────────────────────────────────────────
    publicationCard: {
      unknownProduct: "Unknown product",
      noStore: "No store",
      user: "User",
      validations: "validations",
      reports: "reports",
      validating: "Validating...",
      validate: "✓ Validate",
      validated: "✓ Validated",
      report: "⚠ Report",
      delete: "🗑 Delete",
      deleting: "...",
      viewMore: "View more",
      photoExpand: "🔍 Expand",
      notAvailable: "Publication not available",
      confirmDelete: "Delete publication?",
      reportTitle: "Report publication",
      reportTypeLabel: "Report type:",
      reportSelect: "Select...",
      fakePrice: "Fake price",
      wrongPhoto: "Wrong photo",
      spam: "Spam",
      offensive: "Offensive content",
      cancel: "Cancel",
      sending: "Sending...",
      expand: "Expand",
      collapse: "Collapse",
      closePhotoLabel: "Close enlarged photo",
      validateLabel: (name) => `Validate publication of ${name}`,
      reportLabel: (name) => `Report publication of ${name}`,
      deleteLabel: (name) => `Delete publication of ${name}`,
      viewMoreLabel: (name) => `View more details of ${name}`,
      photoExpandLabel: (expanded, name) => `${expanded ? "Collapse" : "Expand"} photo of ${name}`,
    },

    // ── Price filter ──────────────────────────────────────────────────────────
    priceFilter: {
      title: "Filters",
      product: "🛒 Product",
      store: "🏪 Store",
      productPlaceholder: "Search product...",
      storePlaceholder: "Search store...",
      minPrice: "💰 Minimum price",
      maxPrice: "💰 Maximum price",
      distance: "📍 Maximum distance (km)",
      distancePlaceholder: "No limit",
      sortBy: "📊 Sort by",
      recent: "Most recent",
      validated: "Most validated",
      cheapest: "Cheapest",
      clearFilters: "🗑 Clear filters",
      activeFilter: "1 active filter",
      activeFilters: (n) => `${n} active filters`,
      maxLabel: (val) => `Max $${val}`,
    },

    // ── Stores ────────────────────────────────────────────────────────────────
    storesPage: {
      title: "Stores",
      subtitle: "Explore stores registered by the community.",
      createBtn: "Create store",
      createBtnLabel: "Create new store",
      empty: "No stores registered yet.",
      comingSoon: "The stores list will be available soon.",
      searchPlaceholder: "Search store by name...",
      loading: "Loading stores...",
      errorLoading: "Error loading stores",
      physical: "Physical",
      virtual: "Virtual",
      viewDetail: "View detail",
      storeDetail: {
        title: "Store detail",
        close: "Close",
        address: "Address",
        website: "Website",
        noAddress: "No address registered",
        type: "Type",
        featuredProducts: "Recent publications",
        noProducts: "No publications yet",
        mapLoadError: "Could not load map",
        noLocation: "Virtual store – no physical location",
        loadingProducts: "Loading publications...",
        visitWebsite: "Visit website",
        evidences: "Store photos",
        noEvidences: "No evidence photos registered.",
      },
    },

    // ── Create store ──────────────────────────────────────────────────────────
    createStore: {
      title: "🏪 Create store",
      subtitle: "Register a physical or virtual store. For physical stores you can attach up to 3 evidence files.",
    },

    // ── Store form ────────────────────────────────────────────────────────────
    storeForm: {
      nameLabel: "Store name",
      namePlaceholder: "Ex: Central Supermarket",
      typeLabel: "Store type",
      urlLabel: "Virtual store URL",
      urlPlaceholder: "https://mystore.com",
      submit: "Create store",
      submitting: "Creating store...",
    },

    // ── Store type ────────────────────────────────────────────────────────────
    storeType: {
      physical: "🏬 Physical store",
      virtual: "🌐 Virtual store",
      ariaLabel: "Store type",
    },

    // ── Store map ─────────────────────────────────────────────────────────────
    storeMap: {
      title: "📍 Store location",
      addressPlaceholder: "Ex: 10th Street #25-30, Bogotá",
      searchBtn: "Search address",
      latPlaceholder: "Latitude",
      lonPlaceholder: "Longitude",
      applyBtn: "Apply",
      useLocationBtn: "Use my current location",
      gettingLocation: "Getting location…",
      centerMap: "Center map",
      viewOSM: "View point on OpenStreetMap",
      footer: "Viewer: Leaflet + OpenStreetMap. Geocoding: Nominatim (free with usage limits).",
      statusResolving: "Resolving address...",
      statusAddressUpdated: "Address updated from selected location.",
      statusInvalidCoords: "Enter valid latitude and longitude.",
      statusSearching: "Searching address...",
      statusFound: "Address found and location updated.",
      statusNoAddress: "Write an address to search for it.",
      statusGetting: "Getting location...",
      statusCenterSelect: "Select a valid location to center the map.",
      statusCentered: "Map centered on the selected location.",
      geoPrefix: "Geo:",
    },

    // ── Store evidence ────────────────────────────────────────────────────────
    storeEvidence: {
      title: "🖼 Store evidence",
      addEvidence: "Add evidence",
      limitReached: "Limit reached (maximum 3 images)",
      remove: "Remove",
      altText: "Evidence",
    },

    // ── Publication detail ────────────────────────────────────────────────────
    publicationDetail: {
      closeModal: "Close publication detail",
      noName: "Unnamed product",
      unit: "Unit:",
      noDescription: "No description available",
      publishedBy: "Published by:",
      unknownUser: "Unknown user",
      score: "Score:",
      votes: "Votes:",
      comments: "Comments",
      noComments: "No comments yet.",
      commentPlaceholder: "Write a comment...",
      replyPlaceholder: "Write your reply...",
      addCommentBtn: "Comment",
      replyBtn: "Reply",
      cancelReply: "Cancel",
      deleteComment: "Delete",
      replyingTo: "Replying to",
      loginToComment: "Sign in to comment.",
      storeLocation: "Store location",
      noCoordinates: "No coordinates available for this store.",
      virtualStoreLink: "Go to the virtual store link",
      mapAria: "Store location map",
      mapError: "Map error:",
      mapErrorDetails: "Check the console (F12) for more details",
    },

    // ── Relative time ─────────────────────────────────────────────────────────
    timeAgo: {
      justNow: "just now",
      minutes: (n) => `${n} minute${n !== 1 ? "s" : ""} ago`,
      hours: (n) => `${n} hour${n !== 1 ? "s" : ""} ago`,
      days: (n) => `${n} day${n !== 1 ? "s" : ""} ago`,
      weeks: (n) => `${n} week${n !== 1 ? "s" : ""} ago`,
      months: (n) => `${n} month${n !== 1 ? "s" : ""} ago`,
      years: (n) => `${n} year${n !== 1 ? "s" : ""} ago`,
    },

    // ── Publication form ──────────────────────────────────────────────────────
    publicationForm: {
      title: "Publish Price",
      success: "✓ Publication created successfully",
      errorFallback: "Error creating publication",
      unknownError: "Unknown error",
      productLabel: "Product",
      productPlaceholder: "Type the product name...",
      storeLabel: "Store",
      storePlaceholder: "Type the store name...",
      searching: "Searching...",
      noResults: "No results",
      createProduct: (name) => `+ Create "${name}"`,
      createStore: (name) => `+ Create store "${name}"`,
      productSelected: "✓ Product selected",
      storeSelected: "✓ Store selected",
      productRequired: "Select or create a product",
      storeRequired: "Select or create a store",
      priceLabel: "Price",
      currencyLabel: "Currency",
      descriptionLabel: "Description (optional)",
      descriptionPlaceholder: "Ex: Good condition, fair price",
      photoLabel: "Product photo",
      geoDetected: "Detected location:",
      submitting: "Publishing...",
      submitBtn: "Confirm publication",
      priceRequired: "Price must be greater than 0",
      photoRequired: "Photo is required",
      descriptionMax: "Maximum 500 characters",
    },

    // ── Admin Dashboard ───────────────────────────────────────────────────────
    adminDashboard: {
      navOverview: "Overview",
      navUsers: "Users",
      navContent: "Content",
      navReports: "Reports",
      navConfig: "Config",
      overviewTitle: "Control panel",
      overviewSub: "General overview of the NØSEE platform",
      statUsers: "Total users",
      statPubs: "Publications today",
      statValidations: "Validations today",
      statReports: "Pending reports",
      recentUsers: (n) => `Recent users (${n})`,
      viewAll: "View all →",
      noUsers: "No registered users yet",
      usersTitle: "User management",
      usersCount: (n) => `${n} registered users`,
      loadingDots: "Loading...",
      loadingUsers: "Loading users...",
      contentTitle: "Content management",
      contentSub: "Price publications on the platform — admin can delete any",
      filterAll: "All",
      filterActive: "Active",
      filterPending: "Pending",
      filterExpired: "Expired",
      loadingPubs: "Loading publications...",
      noPubsView: "No publications in this view",
      reportsTitle: "Community reports",
      reportsSub: (n, r) => `${n} reports • ${r} resolved in this session`,
      reportsAllDone: (r) => `All reviewed — ${r} resolved in this session`,
      reportsNone: "No reports in this view",
      filterPendingReports: "Pending",
      filterResolved: "Resolved",
      filterAllReports: "All",
      filterStatusLabel: "Status",
      filterTypeLabel: "Report type",
      filterSortLabel: "Order",
      sortRecent: "Most recent",
      sortOldest: "Oldest",
      summaryByStatus: "Count by status",
      summaryByType: "Count by type",
      statusLabels: {
        PENDING: "Pending",
        IN_REVIEW: "In review",
        RESOLVED: "Resolved",
        REJECTED: "Rejected",
      },
      noReportsPending: "No pending reports ✓",
      loadingReports: "Loading reports...",
      configTitle: "System configuration",
      configSub: "Global parameters of the NØSEE platform",
      repTitle: "Reputation system",
      cancel: "Cancel",
      save: "Save",
      editBtn: "✎ Edit",
      catsTitle: "Product categories",
      catsCount: (n) => `${n} categories`,
      newCatPlaceholder: "New category name...",
      createBtn: "+ Create",
      loadingCats: "Loading categories...",
      noCats: "No categories registered",
      productsCount: (n) => `${n} products`,
      banTitle: "⊗ Ban user",
      unbanTitle: "✓ Unban user",
      banDesc1: "You are about to ban",
      banDesc2: ". Their account will be blocked and",
      banDescStrong: "all their active publications will be hidden",
      banDesc3: ".",
      unbanDesc1: "You are about to restore access for",
      unbanDesc2: ". They will be able to log in normally.",
      cancelBtn: "Cancel",
      confirmBanBtn: "Yes, ban",
      confirmUnbanBtn: "Yes, unban",
      reportTypes: {
        fake_price: "Fake price",
        wrong_photo: "Wrong photo",
        spam: "Spam",
        offensive: "Offensive content",
      },
      severityLabels: { alta: "HIGH", media: "MEDIUM", baja: "LOW" },
      colUser: "User",
      colRole: "Role",
      colRep: "Rep.",
      colStatus: "Status",
      colActions: "Actions",
      colProduct: "Product",
      colStore: "Store",
      colPrice: "Price",
      colAuthor: "Author",
      colDate: "Date",
      colAction: "Action",
      savingRole: "Saving...",
      banBtn: "Ban",
      unbanBtn: "Unban",
      statusActive: "active",
      statusBanned: "banned",
      resolvedBadge: "RESOLVED",
      labelPublication: "Publication",
      labelReportedBy: "Reported by",
      labelReportedUser: "Reported user",
      deletePublicationBtn: "🗑 Delete publication",
      banUserBtn: "⊗ Ban user",
      dismissBtn: "↩ Dismiss",
      viewReportDetailBtn: "View details",
      reportDetailTitle: "Report details",
      reportDetailSubtitle: (id) => `ID: ${id}`,
      labelDescription: "Description",
      labelEvidence: "Evidence",
      labelActionTaken: "Action taken",
      labelModNotes: "Moderator notes",
      saveReportBtn: "Save review",
      reportSavedOk: "Review saved successfully",
      pubStatusActive: "active",
      pubStatusPending: "pending",
      pubStatusRejected: "rejected",
      pubStatusExpired: "expired",
      pubVisible: "Visible",
      pubHiddenStatus: "Hidden",
      filterVisible: "Visible",
      filterHidden: "Hidden",
      pubTotalLabel: (n) => `${n} publications total`,
      pubHiddenLabel: (n) => `${n} not visible`,
      viewPubBtn: "View detail",
      editPubTitle: "Edit publication",
      pubDetailTitle: "Publication detail",
      pubVisibilityLabel: "Visibility",
      pubPriceLabel: "Price",
      pubProductLabel: "Product",
      pubStoreLabel: "Store",
      pubAuthorLabel: "Author",
      pubRepLabel: "Reputation",
      pubDateLabel: "Published",
      pubDescriptionLabel: "Description",
      pubConfidenceLabel: "Confidence",
      pubIsActiveLabel: "Visible on platform",
      pubIsHiddenLabel: "Hidden (not visible)",
      toggleVisibleBtn: "Show publication",
      toggleHideBtn: "Hide publication",
      savePubBtn: "Save changes",
      pubSavedOk: "Publication updated successfully",
      errorEditPub: (e) => `Error editing: ${e}`,
      errorEditPubGeneric: "Error editing the publication.",
      noName: "No name",
      confirmDeletePub: "Delete this publication permanently?",
      errorChangeRole: (e) => `Error changing role: ${e}`,
      errorChangeRoleGeneric: "Error changing role. Try again.",
      errorLoadUsers: "Could not load users",
      errorConnect: "Error connecting to the server",
      retry: "Retry",
      errorStatus: "Error changing status.",
      errorDeletePub: (e) => `Error deleting: ${e}`,
      errorDeletePubGeneric: "Error deleting publication.",
      errorUpdateReport: "Could not update report",
      errorCreateCat: (e) => e || "Error creating category",
      deletedPub: "Deleted publication",
      anonymous: "Anonymous",
      unknown: "Unknown",
    },

    // ── Moderator Dashboard ───────────────────────────────────────────────────
    moderatorDashboard: {
      navReports: "Reports",
      navFeed: "Feed",
      navHistory: "History",
      reportsTitle: "Pending reports",
      reportsSub: (n) => `${n} reports awaiting review`,
      reportsAllDone: "All up to date ✓",
      resolvedToday: (n) => `${n} resolved today`,
      loadingReports: "Loading reports...",
      noReportsTitle: "No pending reports",
      noReportsSub: "The platform is clean. Good work.",
      feedTitle: "Feed with moderation controls",
      feedSub: "View all publications with options to delete or ban content",
      historyTitle: "Action history",
      historySub: "Record of all moderations performed by this moderator",
      comingSoon: "Coming soon",
      labelPublication: "Publication",
      labelReportedBy: "Reported by",
      labelReportedUser: "Reported user",
      deletePublicationBtn: "🗑 Delete publication",
      banUserBtn: "⊗ Ban user",
      dismissBtn: "↩ Dismiss",
      reportTypes: {
        fake_price: "Fake price",
        wrong_photo: "Wrong photo",
        spam: "Spam",
        offensive: "Offensive content",
      },
      severityLabels: { alta: "HIGH", media: "MEDIUM", baja: "LOW" },
      statusLabels: {
        PENDING: "Pending",
        IN_REVIEW: "In review",
        RESOLVED: "Resolved",
        REJECTED: "Rejected",
      },
      viewReportDetailBtn: "View details",
      reportDetailTitle: "Report details",
      reportDetailSubtitle: (id) => `ID: ${id}`,
      filterStatusLabel: "Status",
      labelDescription: "Description",
      labelEvidence: "Evidence",
      labelActionTaken: "Action taken",
      labelModNotes: "Moderator notes",
      saveReportBtn: "Save review",
      reportSavedOk: "Review saved successfully",
      cancel: "Cancel",
      errorUpdateReport: "Could not update report",
      actionConfirmBan: (user) => `You are about to ban ${user}. Their account will be blocked.`,
      actionConfirmDismiss: "You are about to dismiss this report.",
      actionConfirmTitle: "Confirm action",
      actionNotesLabel: "Internal notes (optional)",
      actionConfirmBtn: "Confirm",
      deletedPub: "Deleted publication",
      anonymous: "Anonymous",
      unknown: "Unknown",
    },

    // ── Dealer Dashboard ──────────────────────────────────────────────────────
    dealerDashboard: {
      onlineLabel: "Online",
      navActive: "Active orders",
      navRoute: "My route",
      navHistory: "History",
      navEarnings: "Earnings",
      statActive: "Active",
      statToday: "Today",
      statEarned: "Earned",
      activeTitle: "Active orders",
      activeSub: (n) => `${n} in progress`,
      noOrders: "No active orders. Wait for new assignments.",
      historyTitle: "Order history",
      historySub: "Your latest deliveries",
      routeTitle: "Route map",
      routeSub: "Optimal route visualization between stores and destinations",
      earningsTitle: "Earnings panel",
      earningsSub: "Summary of daily, weekly earnings and commissions",
      comingSoon: "Coming soon",
      statusPendiente: "Pending",
      statusComprando: "Shopping",
      statusEnCamino: "On the way",
      statusLlegando: "Arriving",
      statusEntregado: "Delivered",
      statusCancelado: "Cancelled",
      nextPendiente: "Start shopping →",
      nextComprando: "Go deliver →",
      nextEnCamino: "Arrived →",
      nextLlegando: "Mark delivered ✓",
      advance: "Advance →",
    },
  },
};

// ── Contexto ──────────────────────────────────────────────────────────────────
const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => readStoredLang());

  const setLang = (code) => {
    if (!SUPPORTED_LANGS.includes(code)) return;
    setLangState(code);
  };

  // Persist and apply lang to DOM
  useEffect(() => {
    try {
      window.localStorage.setItem(LANG_KEY, lang);
    } catch {
      // ignore
    }
    document.documentElement.lang = lang;
  }, [lang]);

  const t = TRANSLATIONS[lang];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}

export const LANG_OPTIONS = [
  { code: "es-MX", label: "🇨🇴 Español (Colombia)" },
  { code: "en-US", label: "🇺🇸 English (USA)" },
];
