apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true
    jsonData:
      timeInterval: "15s"
      httpMethod: GET
    version: 1
    editable: false
