/**
 * publicationFormStyles.js
 *
 * CSS-in-JS style objects for PublicationForm and related components.
 */

export const styles = {
  container: {
    maxWidth: "600px",
    margin: "0 auto",
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-md)",
    padding: "24px",
  },
  title: {
    fontSize: "20px",
    fontWeight: 700,
    margin: "0 0 20px 0",
    color: "var(--text-primary)",
  },
  successAlert: {
    background: "var(--success-soft)",
    border: "1px solid rgba(74,222,128,0.3)",
    color: "var(--success)",
    padding: "12px 16px",
    borderRadius: "var(--radius-sm)",
    marginBottom: "16px",
    fontSize: "13px",
    fontWeight: 500,
  },
  errorAlert: {
    background: "var(--error-soft)",
    border: "1px solid rgba(248,113,113,0.3)",
    color: "var(--error)",
    padding: "12px 16px",
    borderRadius: "var(--radius-sm)",
    marginBottom: "16px",
    fontSize: "13px",
    fontWeight: 500,
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
  },
  label: {
    fontSize: "13px",
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: "6px",
  },
  required: {
    color: "var(--error)",
  },
  input: {
    padding: "10px 12px",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-sm)",
    fontSize: "13px",
    fontFamily: "inherit",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  },
  inputError: {
    border: "1px solid var(--error)",
  },
  inputGroup: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  currencyPrefix: {
    position: "absolute",
    left: "12px",
    fontSize: "13px",
    color: "var(--text-muted)",
    pointerEvents: "none",
  },
  inputWithPrefix: {
    padding: "10px 12px 10px 28px",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-sm)",
    fontSize: "13px",
    fontFamily: "inherit",
    width: "100%",
    outline: "none",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  },
  select: {
    padding: "10px 12px",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-sm)",
    fontSize: "13px",
    fontFamily: "inherit",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    WebkitTextFillColor: "var(--text-primary)",
    opacity: 1,
  },
  textarea: {
    padding: "10px 12px",
    border: "1px solid var(--border)",
    borderRadius: "var(--radius-sm)",
    fontSize: "13px",
    fontFamily: "inherit",
    minHeight: "80px",
    resize: "vertical",
    outline: "none",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  },
  charCount: {
    fontSize: "12px",
    color: "var(--text-muted)",
    marginTop: "4px",
    textAlign: "right",
  },
  errorText: {
    color: "var(--error)",
    fontSize: "12px",
    marginTop: "4px",
  },
  row: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  autocompleteContainer: {
    position: "relative",
  },
  dropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderTop: "none",
    borderRadius: "0 0 var(--radius-sm) var(--radius-sm)",
    maxHeight: "220px",
    overflowY: "auto",
    zIndex: 50,
    boxShadow: "var(--shadow-md)",
  },
  dropdownItem: {
    padding: "10px 12px",
    cursor: "pointer",
    fontSize: "13px",
    borderBottom: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    color: "var(--text-primary)",
    background: "var(--bg-elevated)",
  },
  dropdownCreate: {
    color: "var(--accent)",
    fontWeight: 600,
    borderTop: "1px solid var(--border-soft)",
  },
  dropdownReportBtn: {
    flexShrink: 0,
    background: "rgba(220, 38, 38, 0.15)",
    border: "1.5px solid rgba(220, 38, 38, 0.35)",
    borderRadius: "50%",
    width: "20px",
    height: "20px",
    cursor: "pointer",
    fontSize: "11px",
    fontWeight: 800,
    color: "rgba(220, 38, 38, 0.9)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    margin: "0 8px",
  },
  dropdownItemActive: {
    background: "#fff0eb",
    outline: "2px solid #ff6b35",
    outlineOffset: "-2px",
  },
  dropdownState: {
    padding: "10px 12px",
    fontSize: "13px",
    color: "var(--text-secondary)",
    fontWeight: "500",
    background: "var(--bg-surface)",
  },
  dropdownSub: {
    fontSize: "11px",
    color: "var(--text-secondary)",
  },
  dropdownDistance: {
    fontSize: "11px",
    color: "var(--accent)",
    fontWeight: 600,
  },
  selectedBadge: {
    fontSize: "12px",
    color: "var(--success)",
    marginTop: "4px",
  },
  infoText: {
    marginTop: "4px",
    fontSize: "12px",
    color: "var(--text-secondary)",
  },
  inputDetecting: {
    border: "1px solid var(--accent)",
    padding: "10px 32px 10px 12px",
  },
  storeDetectingSpinner: {
    position: "absolute",
    right: "10px",
    top: "50%",
    marginTop: "-8px",
    fontSize: "16px",
    color: "var(--accent)",
    pointerEvents: "none",
    display: "inline-block",
  },
  autoStoreDetectingBanner: {
    marginTop: "6px",
    padding: "7px 10px",
    borderRadius: "var(--radius-sm)",
    background: "var(--accent-soft)",
    border: "1px solid var(--accent-glow)",
    color: "var(--accent)",
    fontSize: "12px",
    fontWeight: 500,
  },
  autoStoreFoundBanner: {
    marginTop: "6px",
    padding: "7px 10px",
    borderRadius: "var(--radius-sm)",
    background: "var(--success-soft)",
    border: "1px solid rgba(74,222,128,0.3)",
    fontSize: "12px",
    display: "flex",
    alignItems: "center",
    gap: "5px",
    flexWrap: "wrap",
  },
  autoStoreFoundIcon: {
    flexShrink: 0,
  },
  autoStoreFoundText: {
    color: "var(--success)",
    fontWeight: 600,
  },
  autoStoreChangeHint: {
    color: "var(--text-muted)",
    fontStyle: "italic",
  },
  geoInfo: {
    background: "var(--accent-soft)",
    border: "1px solid var(--accent-glow)",
    color: "var(--accent)",
    padding: "10px 12px",
    borderRadius: "var(--radius-sm)",
    fontSize: "12px",
  },
  submitBtn: {
    padding: "13px 24px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid var(--accent)",
    fontSize: "14px",
    fontWeight: 600,
    cursor: "pointer",
    background: "var(--accent)",
    color: "#080C14",
    marginTop: "4px",
  },
  inlineActionBtn: {
    padding: "10px 16px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid var(--border-soft)",
    fontSize: "13px",
    fontWeight: 600,
    minHeight: "44px",
    minWidth: "44px",
    marginRight: "8px",
    marginBottom: "8px",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  scanBtn: {
    padding: "4px 10px",
    borderRadius: "var(--radius-sm)",
    border: "1px solid var(--border-soft)",
    fontSize: "12px",
    fontWeight: 600,
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    cursor: "pointer",
  },
};
